
test_that("logical has_length() works correctly", {
  expect_true(has_length(2))
  expect_true(has_length(NA))
  expect_true(has_length(NA_character_))
  expect_true(has_length(1L))
  expect_true(has_length(LETTERS))
  expect_true(has_length("S"))
  expect_true(has_length(factor("S")))
  expect_false(has_length(character(0)))
  expect_false(has_length(numeric(0)))
  expect_false(has_length(list()))
  expect_false(has_length(data.frame()))
  expect_false(has_length(NULL))
})

test_that("logical len_one() works correctly", {
  expect_false(len_one(NULL))
  expect_false(len_one(list()))
  expect_false(len_one(character()))
  expect_false(len_one(LETTERS))
  expect_false(len_one(1:10))
  expect_true(len_one(NA))
  expect_true(len_one(NA_real_))
  expect_true(len_one(NA_character_))
  expect_true(len_one(logical(1)))
  expect_true(len_one(character(1)))
  expect_true(len_one("A"))
  expect_true(len_one("A"))
  expect_true(len_one(1.5))
  expect_true(len_one(1L))
})

test_that("is_chr() works correctly", {
  expect_true(is_chr("A"))
  expect_true(is_chr(character(1)))
  expect_true(is_chr(NA_character_))
  expect_false(is_chr(NA))
  expect_false(is_chr(character(2)))
  expect_false(is_chr(c("A", "B")))
  expect_false(is_chr(1.5))
  expect_false(is_chr(1L))
  expect_false(is_chr(TRUE))
})

test_that("is_dbl() works correctly", {
  expect_true(is_dbl(1.5))
  expect_true(is_dbl(double(1)))
  expect_true(is_dbl(numeric(1)))
  expect_true(is_dbl(NA_real_))
  expect_false(is_dbl(NA_character_))
  expect_false(is_dbl(double(2)))
  expect_false(is_dbl(1:5))
  expect_false(is_dbl("A"))
  expect_false(is_dbl(1L))
  expect_false(is_dbl(TRUE))
})

test_that("is_lgl() works correctly", {
  expect_true(is_lgl(TRUE))
  expect_true(is_lgl(logical(1)))
  expect_true(is_lgl(NA))
  expect_false(is_lgl(NA_character_))
  expect_false(is_lgl(logical(2)))
  expect_false(is_lgl(c(TRUE, FALSE)))
  expect_false(is_lgl("A"))
  expect_false(is_lgl(1.5))
  expect_false(is_lgl(1L))
})

test_that("is_int() works correctly", {
  expect_true(is_int(1L))
  expect_true(is_int(integer(1)))
  expect_true(is_int(NA_integer_))
  expect_false(is_int(NA))
  expect_false(is_int(NA_character_))
  expect_false(is_int(integer(2)))
  expect_false(is_int(1:2L))
  expect_false(is_int("A"))
  expect_false(is_int(1.5))
  expect_false(is_int(TRUE))
})
